import type { ProfileWithOrg } from "@/lib/types/database";

export const DUMMY_PROFILE: ProfileWithOrg = {
  id: "00000000-0000-4000-8000-000000000001",
  email: "jude@celerey.co",
  first_name: "Jude",
  last_name: "Preview",
  preferred_name: "Jude",
  job_title: "Chief Executive Officer",
  role: "ceo",
  status: "active",
  business_unit_id: null,
  department_id: null,
  team_id: null,
  manager_id: null,
  phone: null,
  avatar_url: null,
  start_date: null,
  annual_leave_entitlement: 25,
  employee_number: "JA-PREVIEW",
  personal_email: null,
  date_of_birth: null,
  gender: null,
  employee_category: "employee",
  work_type: "hybrid",
  employment_type: "full_time",
  office_location: "Accra HQ",
  probation_end_date: null,
  termination_date: null,
  leaving_reason: null,
  nationality: "Ghanaian",
  national_id: null,
  ssnit_number: null,
  tin_number: null,
  address_line: null,
  city: "Accra",
  country: "Ghana",
  last_login_at: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  business_unit: {
    id: "00000000-0000-4000-8000-000000000010",
    name: "JA Group",
    slug: "ja-group",
  },
  department: {
    id: "00000000-0000-4000-8000-000000000011",
    name: "Executive",
    slug: "executive",
  },
  manager: null,
  isManager: true,
};
